env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  array-bracket-newline:
    - error
    - multiline: true
  array-bracket-spacing: error
  # https://github.com/prettier/eslint-config-prettier#arrow-body-style-and-prefer-arrow-callback
  # https://eslint.org/docs/rules/arrow-body-style
  arrow-body-style:
    - error
    - as-needed
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  # siehe @typescript-eslint/brace-style
  brace-style: 0
  camelcase: error
  comma-dangle: 0
  # siehe @typescript-eslint/comma-spacing
  comma-spacing: 0
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  # https://github.com/prettier/eslint-config-prettier#curly
  # https://eslint.org/docs/rules/curly
  curly:
    - error
    - all
  default-case: error
  default-case-last: error
  default-param-last: error
  # siehe @typescript-eslint/dot-notation
  dot-notation: 0
  eqeqeq: error
  eol-last: error
  for-direction: error
  # siehe @typescript-eslint/func-call-spacing
  func-call-spacing: 0
  func-name-matching: error
  func-names:
    - error
    - never
  getter-return: error
  grouped-accessor-pairs: error
  # siehe @typescript-eslint/key-spacing
  key-spacing: 0
  keyword-spacing: error
  # wegen //NOSONAR
  #line-comment-position: error
  linebreak-style: error
  logical-assignment-operators: error
  max-classes-per-file: error
  max-depth: error
  # https://github.com/prettier/eslint-config-prettier#max-len
  # https://eslint.org/docs/rules/max-len
  max-len:
    - error
    - ignoreComments: true
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreUrls: true
  max-nested-callbacks:
    - error
    - max: 4
  max-params: error
  max-statements:
    - error
    - max: 25
  max-statements-per-line: error
  new-parens: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  # https://github.com/prettier/eslint-config-prettier#no-confusing-arrow
  # https://eslint.org/docs/rules/no-confusing-arrow
  no-confusing-arrow:
    - error
    - allowParens: false
  no-console: 0
  no-constant-binary-expression: error
  no-constructor-return: error
  no-continue: error
  no-dupe-class-members: 0
  # siehe import/no-duplicates
  #no-duplicate-imports: error
  no-else-return: error
  no-empty-static-block: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  # siehe @typescript-eslint/no-extra-parens
  no-extra-parens: 0
  # siehe @typescript-eslint/no-extra-semi
  no-extra-semi: 0
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  # siehe @typescript-eslint/no-invalid-this
  no-invalid-this: 0
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  # siehe @typescript-eslint/no-loss-of-precision
  no-loss-of-precision: off
  # siehe @typescript-eslint/no-magic-numbers
  no-magic-numbers: 0
  no-multi-assign: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-native-nonconstructor: error
  no-new-object: error
  no-new-wrappers: error
  no-param-reassign: error
  no-promise-executor-return: error
  no-proto: error
  no-redeclare: 0
  # siehe @typescript-eslint/no-restricted-imports
  no-restricted-imports: 0
  no-restricted-properties: error
  # https://github.com/prettier/eslint-config-prettier#no-sequences
  no-restricted-syntax:
    - error
    - SequenceExpression
  no-return-assign: error
  # siehe @typescript-eslint/return-await
  no-return-await: 0
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  # siehe @typescript-eslint/no-shadow
  no-shadow: 0
  no-shadow-restricted-names: error
  no-tabs: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-underscore-dangle:
    - error
    - allow: ['_id', '__v']
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-expressions: error
  no-unused-private-class-members: error
  # siehe @typescript-eslint/no-unused-vars
  no-unused-vars: 0
  no-use-before-define:
    - error
    - functions: false
      classes: false
  no-useless-call: error
  no-useless-catch: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-rename: error
  no-useless-return: error
  no-void: error
  no-whitespace-before-property: error
  no-with: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  # siehe @typescript-eslint/object-curly-spacing
  object-curly-spacing: 0
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  object-shorthand: error
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  # siehe @typescript-eslint/padding-line-between-statements
  padding-line-between-statements: 0
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-numeric-literals: error
  #prefer-object-has-own: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals:
    - error
    - disallowRedundantWrapping: true
  prefer-rest-params: error
  prefer-template: error
  quote-props:
    - error
    - as-needed
  # https://github.com/prettier/eslint-config-prettier#quotes
  # https://eslint.org/docs/rules/quotes
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  radix: error
  require-atomic-updates: error
  # siehe @typescript-eslint/require-await
  require-await: 0
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi-spacing: error
  sort-imports: error
  space-before-blocks: error
  # siehe @typescript-eslint/space-before-function-paren
  space-before-function-paren: 0
  space-in-parens: error
  # siehe @typescript-eslint/space-infix-ops
  space-infix-ops: 0
  space-unary-ops: error
  # wegen //NOSONAR
  #spaced-comment: error
  strict: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  wrap-iife: error
  yield-star-spacing: error
  yoda:
    - error
    - never
  '@typescript-eslint/no-explicit-any': 'off'
  'react/react-in-jsx-scope': 'off'
